config/routes.rb
Rails.application.routes.draw do
  resources :books do
    resources :authorships, only: [:create, :destroy]
  end
  resources :authors

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorships
  has_many :books, through: :authorships

  validates :name, presence: true
  validates :birth_year, presence: true, numericality: {only_integer: true}

end

app/models/authorship.rb
class Authorship < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :authorships
  has_many :authors, through: :authorships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.valid?
      @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to author_path(@author)
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path
  end

  private

  def author_params
    params.require(:author).permit(:name, :birth_year, :book_id)
  end
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController


  def create
    Authorship.create(author_id:params[:authorship][:author_id],book_id:params[:book_id])
    redirect_to "/books/#{params[:book_id]}"
  end

  def destroy
    @authorship = Authorship.find(params[:id])
    @book = @authorship.book
    @authorship.destroy
    redirect_to book_path(@book)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @book_authorships = @book.authorships
    @all_authorships = Authorship.all
    @authorship = Authorship.new
    @book_authors = @book.authors
    @all_authors = Author.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
<p><%= f.label :name %>
<%= f.text_field :name %></p>
<p><%= f.label :birth_year %>
<%= f.text_field :birth_year %></p>
<%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %></h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1>Authors!</h1>

<%= link_to 'New Author', new_author_path %>

<ul>
  <% @authors.each do |author| %>
  <li><%= link_to author.name, author %> (b. <%= author.birth_year %>)
  </li>
  <% end %>
</ul>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<h1><%= @author.name %> (b. <%= @author.birth_year %>)</h1>
<%= link_to "Edit #{@author.name}", edit_author_path(@author) %>
<%= button_to "Delete #{@author.name}", "/authors/#{@author.id}", {:method => :delete} %>

app/views/books/index.html.erb
<h1>Books!</h1>
<ul>
<% @books.each do |book| %>
<li><%= link_to book.title, book %> (<%=book.pages%> pages)</li>
<% end %>
<ul>

app/views/books/show.html.erb
<h1><%= @book.title %> (<%= @book.pages %> pages)</h1>
<h2>Authors:</h2>
<ul>
<% @book_authorships.each do |authorship| %>
<li><%= link_to "#{authorship.author.name} (b. #{authorship.author.birth_year})" , author_path(authorship.author) %>
<%= button_to "Remove author", [@book, authorship], {:method => :delete}  %>
<% end %>
</ul>

<%= form_for [@book, @authorship] do |f| %>
<%= f.label :author_id %>
<%= f.collection_select :author_id, Author.all, :id, :name %>
<%= f.submit 'Add Author'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FullSnackRailsPractice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ol>
      <li> <%= link_to 'Books Index', books_path %> </li>
      <li> <%= link_to 'Authors Index', authors_path %></li>
    </ol>
    <hr>
    <%= yield %>
  </body>
</html>